export enum BscTypeKind {
    ArrayType = 'ArrayType',
    BooleanType = 'BooleanType',
    ClassType = 'ClassType',
    DoubleType = 'DoubleType',
    DynamicType = 'DynamicType',
    EnumType = 'EnumType',
    EnumMemberType = 'EnumMemberType',
    FloatType = 'FloatType',
    FunctionType = 'FunctionType',
    IntegerType = 'IntegerType',
    InterfaceType = 'InterfaceType',
    InvalidType = 'InvalidType',
    LongIntegerType = 'LongIntegerType',
    NamespaceType = 'NamespaceType',
    ObjectType = 'ObjectType',
    ReferenceType = 'ReferenceType',
    StringType = 'StringType',
    UninitializedType = 'UninitializedType',
    UnionType = 'UnionType',
    VoidType = 'VoidType'
}
