name: Publish Release

on:
  pull_request:
    types:
        - closed
    paths:
        - 'package.json'
        - 'package-lock.json'

jobs:
  run:
    if: startsWith( github.head_ref, 'release/') && (github.event.pull_request.merged == true)
    uses: rokucommunity/workflows/.github/workflows/publish-release.yml@master
    with:
      release-type: "npm" # "vsce"
      ref: ${{ github.event.pull_request.merge_commit_sha }}
    secrets: inherit
