name: Publish Release

on:
  pull_request:
    types:
      - closed
    paths:
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The release tag that should be published (i.e. `v1.2.3`)"
        required: true

jobs:
  run:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release/')
    uses: rokucommunity/workflows/.github/workflows/publish-release.yml@master
    with:
      release-type: "npm" # or "vsce"
      ref: ${{ github.event.inputs.tag || github.event.pull_request.merge_commit_sha }}
    secrets: inherit

