name: Security Audit
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    #nightly at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18.20.4"
      - run: npm ci
      - run: npm run audit
